title:              "이햄의 SEO"
tagline:            "마케터가 알아야 하는 개발 이야기"
email:              "earth971@gmail.com"
description:        "디지털 마케터가 꼭 알아야만 하는 검색엔진최적화와 개발 이야기"
author:             "이혜민"
baseurl:            "/"
url:                "https://earth971.github.io"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpeg"

# Social Profiles
twitter_username:   twitter_username
instagram_username: instagram_username
facebook_username:  facebook_username
linkedin_username:  linkedin_username

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

#disqus shortname
disqus:
  shortname: leeham
